### PR TITLE
update wedding.html schedule note

### PR DESCRIPTION
**Pull request by ncd2dq**
Need to hyper link bride / groom address on line 166

### CODE REVIEW

**Comment by ncd2dq** [comment]
@swoloszynski

**Comment by swoloszynski** [comment]
Solid but this PR is against the fork, not the original repo, so that means I can't just merge it into the project. https://help.github.com/articles/creating-a-pull-request-from-a-fork/

**Comment by swoloszynski** [comment]
@ncd2dq

**Comment by swoloszynski** [comment]
Also you can see an example of the hyperlinking here: https://github.com/ncd2dq/greco-wedding/blob/master/index.html#L83

**Comment by swoloszynski** [comment]
@ncd2dq Can you close this? Changes here: https://github.com/swoloszynski/greco-wedding/pull/79/files

**Pull request closed without merging**
